[build]
base = "exampleSite"
publish = "public"
command = "hugo --gc --minify --themesDir ../../ -t repo -b $URL"

[context.production.environment]
HUGO_VERSION = "0.76.3"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "hugo --gc --minify --enableGitInfo -b $DEPLOY_PRIME_URL --themesDir ../../ -t repo"

[context.split1.environment]
HUGO_VERSION = "0.76.3"
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL --themesDir ../../ -t repo"

[context.deploy-preview.environment]
HUGO_VERSION = "0.76.3"

[context.branch-deploy]
command = "hugo --gc --minify -b $DEPLOY_PRIME_URL --themesDir ../../ -t repo"

[context.branch-deploy.environment]
HUGO_VERSION = "0.76.3"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"
